on: 
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ADJECTIVE: great 

name: Create an issue via CLI
permissions:
  contents: read
  issues: write 
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     # - uses: JasonEtco/create-an-issue@v2
      - run: echo "hello"
