name: GitHub Actions Demo
on: 
  workflow_call:
    inputs:
      archetype:
        required: true
        type: string
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Archetype is ${{inputs.archetype}}"
      - run: echo "API key is ${{secrets.OPENAI_API_KEY}}"
