name: GitHub Actions Demo
on: 
  workflow_call:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Archetype is ${{inputs.archetype}}"
      - run: echo "API key is ${{secrets.openai_api_key}}"
